Integrated tests
NalianAchei2020/Metrics-webapp pull request #1
Opened 2023-09-07 13:48 UTC by NalianAchei2020

## 📝 Accomplishments
- Used React documentation.
- Used React components.
- Used React props.
- Used React Router.
- Connect React and Redux.
- Handled events in a React app.
- Write integration tests with a React testing library.
- Used styles in a React app
- Used store, actions, and reducers in React.

2023-09-07 14:27 UTC, mukhammadrizooff requested changes
Hi @NalianAchei2020, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- No linter errors ✔️ 
- Correct GitFlow ✔️ 
- Good implementations ✔️
- Descriptive `README` file ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- [ ] [OPTIONAL] It would be proffesional if you submit your project like : `main` to `dev` not a `dev` to `any branch` 👍🏼 

![image](https://github.com/NalianAchei2020/Metrics-webapp/assets/63915024/376f95e4-42d7-45aa-a9d2-8783bc022372)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-07 14:27 UTC, mukhammadrizooff commented on src/_test_/home.test.js
- [ ] [REQUIRED] Good job so far! You should follow the [design guidelines](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)) including:

Typography: `font face` ✔️, `size` ✔️, and `weight` ✔️  
Layout: `composition` ❌, Elements ❌and `space between elements` ✔️ .

Please pay attention on top of the `❌` options style to your mobile version design because your mobile version difference between Behance 🙏🏼 

![image](https://github.com/NalianAchei2020/Metrics-webapp/assets/63915024/dd0ba209-aa05-409e-8d6f-e216465ba451)

2023-09-07 15:59 UTC, NalianAchei2020 commented on src/_test_/home.test.js
Hi @mukhammadrizooff ,
Please can you explain what all the arrows stand for? I am confused

2023-09-08 16:07 UTC, AbelG101 approved these changes
![](https://media.giphy.com/media/eKfovWZOlOpbTDEX9F/giphy.gif)

# Hi @NalianAchei2020 👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- Consistent Design ✔
- App works as expected ✔
- Correct use of Git Flow ✔
- Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a great summary ✔

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-08 20:12 UTC, merged